### ISSUE TITLE
Read requests

### ISSUE THREAD

**Issue by codetsunami** [HotPocketDev/core#34]
For a large number of HP contracts typical use patterns will be write once read many, or write few read many.

This is something of a problem for the design of HP because reads and writes are both equally intensive, requiring the circulation of the users' input, contract execution, canonical output and so on.

As a possible solution to this we might allow, at the contract author's discretion, the user to send a control message to HP core asking to be put into 'user read mode' (URM)

In this proposed mode:

1. The user's inputs are not circulated into consensus.
2. The user interacts solely with the HP node to which they are connected.
3. The HP node bundles the users' inputs along with any other connected read-mode users.
4. The node executes the contract between consensus executions, with a special flag set in the fdlist.
5. The contract promises not to change the state of the contract.
6. The contract executes read-only instructions against its state and delivers outputs.
7. The HP node delivers those outputs to the user. 
8. The contract can be force terminated early so it does not get in the way of a consensus contract execution. If this happens the user's inputs should be circulated into consensus instead.

Justification:
The Doherty threshold for interactive computing is 400ms. Consensus rounds take typically on the order of 3000 to 10000ms. However the vast majority of user interactions with the vast majority of contracts are likely to be read operations. Therefore if we can lower the response time on typical contract interaction to 400ms, we should.

**Comment by ravinsp** [comment]
If the read-mode user’s inputs and outputs are not circulated in consensus, how can they trust the outputs? It could be that they connected to a compromised node thereby poisoning the output. Is it a risk taken in favor of performance.

**Comment by codetsunami** [comment]
This is true even of non-read mode. If you're connected to a third party's node you have no easy way to ensure that node isn't just feeding you nonsense. I suppose, depending on the type of contract, you could connect independently to a few other nodes to check if the delivered outputs are consistent.

In short you have to run your own node node to avoid trusting a third party. Which is why this is important: https://github.com/HotPocketDev/core/issues/33

The answer is that they would typically be connected to their own non-UNL node, which they know they can trust.

**Comment by codetsunami** [comment]
So this mirrors XRPL's model. 

If you need to interact with the XRPL you can either nominate a third party node and then check the ledger state (after executing a transaction) using second third party node... or you can run your own Rippled node which you know you can trust. The preferred method is the latter.

Rippled nodes are heavy but HP nodes don't need to be.

**Comment by codetsunami** [comment]
As with everything, we should provide advanced features for those who want them but hide them away for simple default cases

**Comment by ravinsp** [comment]
8. The contract can be force terminated early so it does not get in the way of a consensus contract execution. If this happens the user's inputs should be circulated into consensus instead.

I assume the need to force terminate read-mode contract is because we have to give priority to consensus rounds. Read-mode is best-effort. We try to respond as fast as possible in best case, and if we can't (due to consensus contract starting) we choose the second best option. Still, why do we need the read-mode inputs/outputs to be circulated in that "second-best" scenario?

I suggest we send/receive the read-mode inputs/outputs via a separate channel in the fdlist into the contract. Contract should make sure to process read-mode I/O first before anything else so it doesn't change any state during that stage. Hot Pocket will collect read-mode outputs after consensus contract exists and send them back to read-mode users without sending them to consensus. Other 'normal' outputs will participate in consensus.

**Comment by codetsunami** [comment]
I don't want to add any significant complexity for the contract developer. Adding a second channel to fdlist adds significant complexity.

From the contract developer's point of view: if they have configured hotpocket to support user read mode then they should handle executions as usual. In addition to handling executions as usual if they detect a flag in the fdlist structure { readmode: true } then they should not alter state.

The reason for early termination is as you point out to prevent read-mode executions getting in the way of consensus. Particularly if a contract is badly programmed and ends up taking a long time to run. Running two copies of the contract at the same time: one in read mode and one in write mode will produce locking or data corruption depending on filesystem and how contract is opening its files.

An alternative to circulating failed read-mode inputs into consensus is to hold them over until consensus has ended, for another read-mode execution after consensus however this risks making the user wait a long time when they hit this edge case.

A possible "perfect" solution does occur to me. If we implement contract state using FUSE, it would be possible to mount a "previous state" directory consisting of old blocks we have cached anyway. This would allow read-only mode to execute against a slightly old state that is guaranteed not to be updated without getting in the way of ongoing execution.

**Comment by ravinsp** [comment]
Previous-state solution seems very elegant although that would be significant work for Hot Pocket! That would even enable the read-mode contract to run without having to block the consensus contract. We can deliver the promised 'quickness' of read-mode more frequently.

The file system will have to carefully manage the backup snapshot/checkpoint so as to not to allow race conditions for the snapshot itself (consensus contract starting execution and saving backup state while the read-mode contract is running). Instead of FUSE, what if we use a filesystem based snapshot/checkpointing feature/library? eg: https://rsnapshot.org/ or [LVM](https://www.theurbanpenguin.com/maning-lvm-snapshots/). There's the overhead of needing to diversify our engineering toolset.

**Comment by ravinsp** [comment]
We need to come up with a virtual state file system (let's call it hpfs) in order to support read mode. In read mode, we need to always maintain a stable checkpoint of state for read access, while providing the ability for write operations to occur independently of the stable state. @codetsunami 

1. Let's call the stable state with read access as checkpoint 0.
2. Any write operations performed by subsequent consensus contract executions will be maintained in checkpoints 1,2,3...N. Every checkpoint greater than 0 corresponds to a single consensus execution of the smart contract.
3. Read requests can be served solely by checkpoint 0 because it contains a coherent self-sufficient state file/folder structure. We can use libfuse passthrough example with restricted read-only access to achieve this.
4. However, every consensus contract execution needs a read/write file system "view" of the combined/merged state of checkpoints 0..N. This is because files/folders and individual blocks of the same file may be distributed across checkpoints 0..N.

To maintain this merged virtual view of the state file system we need to keep a complete index of the entire list of files/folders and block map of each of those files across checkpoints 0..N. This can be similar to a file allocation table maintained in a mainstream file system.

I suggest using a sqlite database to keep the aforementioned lookup tables/maps. We can also use the same mechanism to store the block/file/dir hashes to support state hash calculation. Although there will be a performance impact going through the sqlite driver, this would simplify the implementation effort, increase the stability of the hpfs code base, and allow for easier future extension.
