### ISSUE TITLE
Loading keys from config

### ISSUE THREAD

**Issue by codetsunami** [HotPocketDev/core#5]
https://github.com/HotPocketDev/core/blob/1a8672b656c7123389744e19e3889836aa727a61/src/main.cpp#L14

Crypto init (sodium_init) should execute first so you can check if the private key in the config corresponds to the public key in the config, and check that every entry in the contract UNL is a valid public key 

If any there is an issue with any key in the config the app should explain the issue and then terminate with a non zero return code without proceeding further 

We may wish to include a way to specify which curve each set of keys / key is for. If we don’t we will have to hard code a single curve which may break forward compatibility of contract config in future

**Comment by ravinsp** [comment]
How I have gone about this is `conf::init()` would read and load config data into in-memory struct in a dumb manner. After that, other subsystems (eg. crypto, comms) would validate the respective config settings that they are responsible for during theit `init()` process.
I have yet to implement pub/sec key validation in `crypto::init()`. Also I'm using `crypto_sign_keypair()` which does not need to specify the asym-key algorithm. I'll find a way to generate keys by specifying the algorithm.

**Comment by ravinsp** [comment]
Since we store the HP version in config, we can use that to determine the default key type used by the specific libsodium version we were using at a particular HP version.
We can also include the key type used in the config, but we don't need to do that if we validate the HP and libsodium version anyway. We should introduce such version/key type check code if and when libsodium changes the default signing key algorithm.

**Comment by codetsunami** [comment]
Best to explicitly specify the key type in the config in case we support different key types later. That way it will be unambiguous when old contracts are used on new versions

**Comment by ravidulashan** [comment]
Fixed #17
