### ISSUE TITLE
Contract state management

### ISSUE THREAD

**Issue by ravinsp** [HotPocketDev/core#8]
Original discussion from HP prototype: https://github.com/codetsunami/hotpocket/issues/2
We need to come up with state management protocol between HP and the smart contract.

**Comment by codetsunami** [comment]
I don’t think we should use a special protocol. I think the smart contract should be allowed to write any state it likes to the state folder and Hot Pocket should do the hard work generating deltas and managing the consensus state. This will allow smart contracts to be written very generally without specific overhead for hotpocket and importantly won’t limit the use of third party libraries in contracts for example SQLite.

For contracts that have many smallish state files this is trivial. Check the file modification time and assume anything that hasn’t been modified at last consensus round has its old hash.

However for contracts that have large files this is not ideal. A contract for example that has a 2 Gb state file that it changes 3 bytes of every execution would require hotpocket to run a full hash back over that file. While possible this wastes a lot of resources.

Ideally then I think hot pocket would provide a filesystem in userspace (fuse) that’s mounted at the /state file for any contract it’s managing. This would then allow hot pocket to efficiently monitor changes to the state while also letting those changes map through to the underlying filesystem

**Comment by codetsunami** [comment]
It requires more investigation but I believe a fuse solution would allow files to be represented as Merkel trees and therefore state information and deltas to be efficiently computed and transmitted

**Comment by codetsunami** [comment]
Investigating FUSE, it looks reasonably simple for us to provide an interception system for the state directory.

https://github.com/libfuse/libfuse/blob/62c1941cc846aeeae04b090d5d24252ba7365a41/example/passthrough.c#L328-L350
```C++
static int xmp_write(const char *path, const char *buf, size_t size,
		     off_t offset, struct fuse_file_info *fi)
{
	int fd;
	int res;
	(void) fi;
	if(fi == NULL)
		fd = open(path, O_WRONLY);
	else
		fd = fi->fh;
	if (fd == -1)
		return -errno;
	res = pwrite(fd, buf, size, offset);
	if (res == -1)
		res = -errno;
	if(fi == NULL)
		close(fd);
	return res;
}
```

This is a concept for how to manage contract state efficiently without imposing significant restrictions on contract developers.

First choose a logical block size corresponding to the minimum read size from a standard SSD e.g: 4mib and a cryptographically secure hash algorithm e.g: SHA512Half.

Next we define canonical contract state as follows:
A map having:
Keys: the filepath starting from the /state/ directory down to the file, e.g. (/state/)foo/bar/file1
Values: if the size file is <= 4mib: the hash of the file, if the file size > 4mib: the root of the merkle tree representing the file. 
```JSON
state = {
"foo/bar/file1": "<hash 1>",
"somerootfile": "<hash 2>"
}
```

Merkle tree:
1. Logical blocks are used to build the merkle tree. The file is decomposed into a sequence of 4mib blocks. These form the leaf nodes of the merkle tree.

2. Each leaf node has a hash which consists simply of HASH(blockdata) (in this case: SHA512H(blockdata))

3. Since a SHA512H is 32 bytes you can fit 131,072 hashes in a parent block. Every 131,072 leaf nodes, the hashes from those blocks (see 2) form a new block which is the parent of all those blocks. Incomplete parent nodes (due to lack of leaf nodes) are still hashed with whatever is in them. Empty blocks are defined as hash of 0. I.e. we force HASH(emptyblock) = 0.

4. For simplicity and transfer efficiency we can fix the tree at one non-leaf non-root layer. This allows filesizes up to 131072*4mib ~= 550gib to be represented. It's conceivable someone might want support for larger files than this so we should make the blocksize user adjustible. However adding more than one non-leaf layer quickly explodes the size of the merkle tree which results in necessary non-trivial negotiation between nodes to avoid transferring more of the tree than is actually required. For simplicity the first version of the production code should fix the size of the tree at 1 non-leaf non-root layer as below.

```
[lvl0] root hash, level overhead = 32b
   |
[lvl1] 131,072 hashes, level overhead = 4mib 
   |
[lvl2] leaf nodes 131,072 * 4mib ~= 550gib, level overhead = 0
```

5. Note that during normal operation smart contracts will pass only their state delta which consists of additions, removals and modifications to the canonical state structure (represented at the start of this post). The transfer of merkle trees would be reserved for state transfer operations.


So a typical contract execution might look something like this:
i. Contract binary runs, modifying 3 bytes at offset X in file Y which is a 3gib file.
ii. FUSE records this alteration into a log made available to hpcore
hpcore:
iii. finds the leafnode to update in its Merkel tree
iv. determines the altered block
v. reads the altered block
vi. hashes the altered block
vii. updates the leaf node in the merkle tree
viii. updates the parent node in the merkle tree
ix. updates the root hash.

**Comment by codetsunami** [comment]
There is an optimisation to the above to avoid doing unnecessary expensive cryptographically secure hashes, although it only saves overhead for small files > 4mib but significantly less than 550gib:

So in the above scheme a 3 byte change to such a file requires computation of 3 SHA512H hashes. However a scheme with similar security requiring just one SHA512H is as follows.

Change the HASH_leaf_node = SHA512H(byteoffsetofblock + filename + blockdata).

Change the HASH_parent_node = XOR(HASH(child1), HASH(child2), ...)

Now when a leaf hash is updated the old hash for that leaf can be scrubbed from the parent nodes by XOR, and the new hash can be added by XOR. It's possible to mutate the tree without changing the root hash by rearranging child hashes, but it isn't possible to change the underlying file because the byte offset is encoded in the leaf hash.

**Comment by ravinsp** [comment]
Still haven’t fully digested this. Thanks for the detailed thoughts and the creative approach. But few questions/thoughts for future reference:

1. How do we ensure contract writes all state changes to the “state” dir? (Maybe we keep it as a requirement and pass the state dir path in the contract arguments?)

2. DOS attack?: an inefficient/malicious contract executing so many tiny update operations so it floods our write logs and merkle tree operations.

3. If the contract is doing multi threaded writes, we will have difficulty managing the hash tree operations.(do we have to worry about this? Does FUSE makes filesystem single-threaded?)

4. Isn’t root hash calculation going to be O(n)? (Regardless of how many leaf blocks were actually changed)

5. I’ve yet to read up on FUSE? Does it offer unified interface on Linux and MacOSX?

**Comment by ravinsp** [comment]
Hey, a simple idea just occurred to me. We don't actually care about the block/layout of the file(s) written by the contract. We just care about the "changeset" so we can make the changeset be exchanged during consensus.
So how about we just use your idea about keeping a write-log and just stop there. Just exchange the write-log hash? Every log line will contain the filepath, offset and length. And we just sort them in a consistent order and hash it. (Sorting is to ensure we get the same order regardless of multi threaded writes)
What do you think? Have I missed anything? It sounds too simple to be correct.

Note. Disregard my point no. 3 in above comment. we don't have that problem because we only operate on the tree AFTER contract execution.

**Comment by codetsunami** [comment]
1. It’s just a requirement for developing a contract. All state you want consensus applied to lives in the state directory. The contract author makes the call as to whether or not they want to store additional state in other locations that is not subject to consensus rounds (such as for example a node specific state)

2. Codius handles the cost of operations. It’s up the contract author to ensure his/her contract is efficient enough. They are providing / paying for their own nodes so if they want to waste their own money they can. The contract programmer is also tasked with ensuring external / end users can’t waste their contracts resources trivially.

3. We simply Mark any block modified by a filesystem operation and then rehash those specific blocks at the end of the contract execution. We don’t hash while the contract is running.

4. The first time a file is brought into /state/ the hash complexity is O(n) where n is the number of blocks in the file. Thereafter the hash complexity is O(u) where u is the number of updated blocks for the execution round. Once we’ve hashed a block once and we know it hasn’t been updated we don’t need to hash it again.

The root hash is always simply the hash of the lvl1 4mb block. Which is a single operation, always O(1), however populating that block is O(n) the first time and O(u) subsequently.


For small contracts typical behaviour would be one hash per updated file per execution. For larger contracts that use databases typical behaviour would be 10s to 100s of hashes per execution.

5. MacOS does have FUSE but I haven’t checked if it’s compatible with the Linux version. Our primary target for hotpocket is actually docker containers, because that’s what codius uses.

**Comment by codetsunami** [comment]
Change logs work fine until you want to add a node to the network that has been absent for say 3 days. Now it has to play forward 3 days worth of change logs. A Merkel tree would allow it to sync instantly without doing a full state transfer, which is the behaviour we want. Even if we use change logs we will still need a state from which the change logs arise, which means maintaining the hash of potentially large files which means either hashing the whole file at regular intervals (expensive) or keeping a Merkel tree as above

**Comment by ravinsp** [comment]
In that case, wouldn't the new node need the actual data file(s) as well to catch up? Without the actual data files it won't be able to operate. Would we also need to think about full state transfer as well (not just the hashes)?

**Comment by codetsunami** [comment]
Correct

So there’s three three scenarios

Either the peer has no state or the peer has an outdated or otherwise invalid state or the peer hash the canonical state (root hash matches last closed ledger)

Last case we do nothing.
First and second cases we transfer Merkel tree.

That peer can then catch up by requesting blocks from various other peers that are missing from their state (which might be empty) until they have the full state up to the point that Merkel tree was sent. They can then play forward the closed ledgers which elapsed while they were collecting state. This would require some sort of block caching so old versions of blocks remain available to be requested for some time.

This is pretty much just BitTorrent but done in such a way that the torrent file can be updated cheaply instead of regenerating the whole torrent every execution

**Comment by codetsunami** [comment]
It occurs to me not everyone is necessarily familiar with BitTorrent so have a read of the Wikipedia https://en.m.wikipedia.org/wiki/BitTorrent

**Comment by ravinsp** [comment]
Based on findings from @ravidulashan it looks like with FUSE, you have to take the full responsibility of the entire filesystem mounted at the "state" directory. This includes, reads, writes, directory listing etc... Since Hot Pocket only needs to capture a log of write operations done to the files, I was wondering whether there was a way to "pass-through" the filesystem write operations to the actual filesystem (ext4 etc..) and just capture the write event with byte offset and length of the write.

I liked the simplicity of 'inotify' events. Unfortunately it doesn't send byte offsets etc.. with the 'IN_MODIFY' event. Otherwise I felt this is the exact model we need as well without implementing a full file system just for tracking files. 
@codetsunami Do you know anything like this? Probably there are reliable file systems implemented on top of libfuse which exposes the notification feature, but I couldn't find one.
My only worry is whether the code snippets we write in FUSE handlers to actually read/write from the disk will be efficient enough and comparable to standard file systems.

**Comment by codetsunami** [comment]
Isn't this the passthrough example provided with libfuse? https://github.com/libfuse/libfuse/blob/master/example/passthrough.c

We should only need to monitor the functions here that modify the contents of, create or delete files. 

It's unlikely the first version will be perfect. Maybe stick to core functionality and we'll clean the hundreds of nasty edge cases like symlinks, hard links, named pipes etc. in a much later version.

**Comment by ravinsp** [comment]
It is named passthrough but it’s not true passthrough. It emulates passthrough by crudely performing the requested actions using equivalent system calls. I’m pretty sure we can find more efficient examples but they all have user code reading/writing actual bytes.

How I imagined passthrough was having no code at all to perform the action. Let the real file system handle it. We would just have pieces of code to grab the nature of the action and log it.

**Comment by ravinsp** [comment]
“We should only need to monitor the functions here that modify the contents of, create or delete files.”
I think this is also not going to work. If you don’t implement a certain handler, your file system is just not going to have that feature. For example, if you don’t implement `readdir` handler, your file system will not have directory listing and will not be compatible with ‘ls’ or file explorer UI.
I think this is the expected way Fuse works. It’s just you and the kernel module. There’s nothing containing a “default” implementation if you don’t provide one. I really hope I’m wrong on this one. :-)

**Comment by ravinsp** [comment]
Preliminary state file block modification tracking based on ptrace has been implemented in https://github.com/HotPocketDev/core/commit/32ef41bfdf650a3673cd0d4db96a7d1c6d5da02f
This is based on https://github.com/codetsunami/file-ptracer/blob/master/trace.cpp

**Comment by ravinsp** [comment]
Merkal tree based file state file block map has been implemented in https://github.com/HotPocketDev/core/commit/a3bc504bf7c2f12031f43cfc1a40d8615b4c46d3
This is based on https://github.com/codetsunami/file-ptracer/blob/master/merkle.cpp
